export const ADD_EXPENSE_REQUEST = 'ADD_EXPENSE_REQUEST';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_FAILURE = 'ADD_EXPENSE_FAILURE';

export const GET_EXPENSES_REQUEST = 'GET_EXPENSES_REQUEST';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_FAILURE = 'GET_EXPENSES_FAILURE';

export const GET_PIECHART_DATA_REQUEST = 'GET_PIECHART_DATA_REQUEST';
export const GET_PIECHART_DATA_SUCCESS = 'GET_PIECHART_DATA_SUCCESS';
export const GET_PIECHART_DATA_FAILURE = 'GET_PIECHART_DATA_FAILURE';